#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 7, 2021 13:47:12 PM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def cancel_startMenu():
    sys.stdout.flush()
    sys.path.append('..\startMenu')
    root.destroy()
    import start_menu
    start_menu.vp_start_gui()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def login_check():
    global w
    print('signup_support.xxx')
    username = w.Entry_USERNAME.get()
    password = w.Entry_USERNAME.get()
    print(username + " " + password)
    if username == "" or password == "" or username.isspace() is True or password.isspace() is True:
        src = w.error_label
        src.configure(text="Error: The details cannot be empty")


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import login
    login.vp_start_gui()




