#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 7, 2021 14:05:35 PM +0200  platform: Windows NT

import sys
from queue import Queue
from threading import Thread
from threading import *
import sys
from socket import *
from time import sleep

conn_q = Queue()
gui_q = Queue()

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def register():
    global w
    messege = "new"
    conn_q.put(messege.encode('latin-1'))
    print('signup_support.xxx')
    username = w.Entry_username.get()
    password = w.Entry_password.get()
    print(username + " " + password)

    if username == "" or password == "" or username.isspace() is True or password.isspace() is True:
        src = w.error_label
        src.configure(text="Error: The details cannot be empty")
    else:
        conn_q.put(username)
        conn_q.put(password)
        server_reply = gui_q.get().decode('latin-1')
        while server_reply == "not valid":
            src = w.error_label
            src.configure(text="Error: this username is taken, try a new one")
            conn_q.put(username)
            conn_q.put(password)
            server_reply = gui_q.get().decode('latin-1')


def cancel_startMenu():
    sys.stdout.flush()
    sys.path.append('..\startMenu')
    root.destroy()
    import start_menu
    start_menu.vp_start_gui()


def client_recv(my_socket):
    while True:
        data = my_socket.recv(1024)
        if data=="":
            print("server close this socket")
            my_socket.close()
            break #get out from thread
        data = data.decode('latin-1')
        print ("client_recv:" + data )
        print("4444",current_thread().name)
        gui_q.put(data)


def client_send():
    print("start client")
    my_socket = socket()
    my_socket.connect(("127.0.0.1",8820))

    recvThread = Thread(target=client_recv, args=(my_socket,))
    recvThread.start()

    while True:
        if not conn_q.empty():
            data = conn_q.get()
            #print ("client_send:" + data)
            print("3333", current_thread().name)
            my_socket.sendall(data.encode('latin-1'))
        sleep(0.05) #sleep a little before check the queue again


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    commThread = Thread(target= client_send, args=())
    commThread.start()
    top.after(100, on_after_elapsed)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import signup

    signup.vp_start_gui()
