#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 6, 2021 18:47:39 AM +0200  platform: Windows NT

import sys
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def startLoginPage():
    sys.stdout.flush()
    sys.path.append('..\loginPage')
    root.destroy()
    import login
    login.vp_start_gui()


def startSigninPage():
    sys.stdout.flush()
    sys.path.append('..\signinnPage')
    root.destroy()
    import signup
    signup.vp_start_gui()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import start_menu
    start_menu.vp_start_gui()




